# CircleCI 2.0 configuration file
#
# config ENVVAR inside circleci project

version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk:latest # custom image in public Docker registry
    filters:
      branches:
        only: master
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "40:5f:47:ef:65:95:40:69:86:77:55:24:16:0a:f1:8b"

      - run:
          name: gcloud auth
          command: gcloud auth list
