# CircleCI 2.0 configuration file
#
# config ENVVAR inside circleci project

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    filters:
      branches:
        only: master
    steps:
      - checkout

      - run:
          name: clone target
          command: git clone https://github.com/romanovsky-vassar/target-ci.git
      - run:
          name: copy latest
          command: cp README.md ./target-ci/docs/index.md
      - run:
          name: s3
          command: |
            cd target-ci
            ls -l
